### ISSUE TITLE
Uncaught Module exceptions should be caught by ModuleManager

### ISSUE THREAD

**Issue by muff1nman** [ColoradoSchoolOfMines/interface_sdk#4]
Exceptions thrown by a Module during it's execution should be caught by the ModuleManager so that we can revert back to the default and continue the runtime loop.

**Comment by muff1nman** [comment]
It should be considered to solve this by spawning new separate processes instead of separate threads for running modules.  This would solve the issue because any exceptions in any spawned threads by the module eventaully have to boil up to the process at which point we could intervene  This may solve many other issues besides this as well as OpenGL may work considering this is how a Processing Sketch spawns its Runner when hitting the run button.

**Comment by muff1nman** [comment]
With e9bc4a63b4ac3124316cbbf55977ec000e2e40ae this issue is fixed.  So much so that we can recover from issues like this:

```
...
[2013-07-13 13:53:00,451 module_executors.ModuleSimpleExecutor]
 >>DEBUG Running module

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at processing.opengl.PGL.swapBuffers(PGL.java:1182)
    at processing.opengl.PGraphicsOpenGL.dispose(PGraphicsOpenGL.java:644)
    at processing.core.PApplet.dispose(Unknown Source)
    at edu.mines.acmX.exhibit.module_management.modules.ProcessingModule.exit(ProcessingModule.java:145)
    at edu.mines.acmX.exhibit.module_management.modules.ProcessingModule$1.windowClosing(ProcessingModule.java:125)
    at java.awt.Window.processWindowEvent(Window.java:2051)
    at java.awt.Window.processEvent(Window.java:2009)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
[2013-07-13 13:53:09,594 module_management.ModuleManager]
 >>INFO Loading jars in [modules]
...
```

This is really cool and increases the stability of the Module Manager by 10 fold.  

However, to get here, we had to strip down.  I'm going to now work on slowly adding back in those things.
